version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REACT_APP_API_URL=http://app:3000/api
    volumes:
      - app-data:/app/data

volumes:
  app-data:
